import {openDB,storeApi,bootstrap,daily,exportDatabase,importDatabase,createMainSession} from './data.js';
import {todayKey,pct,updateWater,completeOnce,exerciseLibrary,editHistoricalSet} from './domain.mjs';
let api,profile,day,screen='today';const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const bar=(value,target,label)=>`<div class="meta"><span>${label}</span><b>${pct(value,target)}%</b></div><div class="bar"><i style="width:${pct(value,target)}%"></i></div>`;
const nav=()=>`<nav class="nav"><div class="nav-inner">${[['today','⌂','TODAY'],['train','↗','TRAIN'],['dominance','◇','DOMINANCE'],['quests','☑','QUESTS'],['profile','◌','PROFILE']].map(([id,icon,label])=>`<button class="${screen===id?'active':''}" data-nav="${id}"><i>${icon}</i>${label}</button>`).join('')}</div></nav>`;
async function transaction(amount,label,reference){if(reference&&await api.get('transactions',reference))return false;const t={id:reference||crypto.randomUUID(),amount,label,at:Date.now()};await api.put('transactions',t);profile.xp+=amount;profile.coins+=Math.max(0,Math.floor(amount/5));await api.put('profiles',profile);return true}
async function mainSession(){return createMainSession(api,day,exerciseLibrary.slice(0,3))}
async function action(name,payload={}){if(name==='water'){updateWater(day,payload.amount);await api.put('daily',day)}if(name==='start-main'){const s=await mainSession();if(s.status==='NOT_STARTED'){s.status='ACTIVE';await api.put('workouts',s)}screen='train'}if(name==='pause-main'){const s=await mainSession();if(s.status==='ACTIVE'){s.status='PAUSED';s.pausedAt=Date.now();await api.put('workouts',s)}}if(name==='complete-set'){const s=await mainSession();if(s.status==='COMPLETED')return;const ex=payload.exercise;const sets=s.sets[ex]||[];sets.push({id:crypto.randomUUID(),reps:payload.reps||10,weight:payload.weight||0,at:Date.now(),edits:[]});s.sets[ex]=sets;s.status='ACTIVE';if(s.exerciseIds.every(id=>(s.sets[id]||[]).length>=3)){if(completeOnce(s,`main-complete-${s.id}`))await transaction(75,'Main Workout Complete',s.completionTransactionId)}await api.put('workouts',s)}if(name==='move-main-tonight'){day.schedule.events.find(x=>x.name==='Main Workout')?.start='7:00 PM';day.schedule.events.find(x=>x.name==='Main Workout')?.end='8:15 PM';await api.put('daily',day)}await render()}
async function today(){const s=await mainSession();return `<header class="top"><div><div class="eyebrow">CAELUM // ONLINE</div><h1>KITTY QUEST 2.0</h1><p>DOMINANCE // BODY MODULE</p></div><div class="orb">◉</div></header><section class="card"><div class="title-row"><div><div class="eyebrow">WATER</div><div class="metric">${day.water.consumed} / ${day.water.goal} oz</div></div><span>💧</span></div>${bar(day.water.consumed,day.water.goal,'Daily hydration')}<div class="quick"><button class="ghost" data-water="-8">−8</button><button class="ghost" data-water="8">+8</button><button class="ghost" data-water="16">+16</button><button class="ghost" data-water="24">+24</button><button class="ghost" id="water-custom">CUSTOM</button></div></section><section class="card"><div class="eyebrow">MAIN WORKOUT</div><div class="title-row"><h2>${s.status==='COMPLETED'?'✓ MAIN WORKOUT COMPLETE':'TOTAL BODY FOUNDATION'}</h2><span>${s.status}</span></div>${bar(Object.values(s.sets).reduce((n,x)=>n+x.length,0),s.exerciseIds.length*3,'Set progress')}<p class="small">${s.status==='COMPLETED'?'Saved permanently for today.':'Main, extra, sport, and custom training are separate sessions.'}</p><button class="primary" data-action="start-main">${s.status==='COMPLETED'?'VIEW SESSION':'START / RESUME'}</button></section><div class="section">READINESS</div><section class="readiness"><div><small>Upper</small><b>82%</b></div><div><small>Core</small><b>77%</b></div><div><small>Lower</small><b>54%</b></div></section><div class="section">TODAY'S SCHEDULE</div><section class="schedule">${day.schedule.events.map(e=>`<article class="item"><time>${e.start}</time><span><b>${e.name}</b><small class="small">${e.context} · ${e.source}${e.fixed?' · locked':''}</small></span></article>`).join('')}</section>`}
async function train(){const s=await mainSession();const cards=exerciseLibrary.slice(0,3).map(ex=>{const n=(s.sets[ex.id]||[]).length;return `<article class="card"><div class="title-row"><div><div class="eyebrow">${n>=3?'COMPLETE':'CURRENT'}</div><h2>${ex.name}</h2></div><span>${n}/3</span></div>${bar(n,3,'Working sets')}<p class="small">${ex.muscles.join(' · ')} · ${ex.safety}</p>${n<3?`<button class="primary" data-set="${ex.id}">COMPLETE SET</button>`:`<button class="ghost" data-history="${ex.id}">VIEW SETS</button>`}</article>`}).join('');return `<h1>TRAIN</h1><div class="notice">${s.status==='PAUSED'?'Paused workout restored. Completed sets are safe.':'Main Workout: '+s.status}</div>${cards}<div class="section">STILL HUNGRY?</div><button class="item" disabled><b>Extra Training</b><small class="small">Phase 2: separate optional sessions without changing Main Workout.</small></button>`}
async function dominance(){return `<h1>DOMINANCE</h1><section class="card"><div class="eyebrow">LEARN → TRAIN → PROVE → DOMINATE → UNLOCK</div><h2>FIRST STRICT PULL-UP</h2>${bar(0,5,'Goal dependency path')}<p class="small">Hangs → scapular control → assisted pull-ups → negatives → grip milestones.</p></section>${exerciseLibrary.map(x=>`<article class="item"><b>${x.name}</b><small class="small">${x.dominance.type} · ${x.progressions.join(', ')}</small></article>`).join('')}`}
async function quests(){return `<h1>QUESTS</h1><section class="card"><b>Daily tracking is Phase 1.</b><p class="small">Workout and routine quests will be derived from dated records, not duplicated checkboxes.</p></section>`}
async function profilePage(){return `<h1>PROFILE</h1><section class="card"><div class="eyebrow">PLAYER</div><h2>${esc(profile.name)}</h2><p>${profile.xp} XP · ${profile.coins} coins</p><button class="ghost" id="export">EXPORT COMPLETE BACKUP</button><label class="ghost" style="display:block;text-align:center;margin-top:8px">RESTORE BACKUP<input id="import" type="file" accept="application/json" hidden></label></section><section class="card"><div class="eyebrow">12-WEEK TRANSFORMATION QUEST</div><h2>Initial configuration</h2><p class="small">216 lb start · 192–204 lb goal range · 175 lb later milestone. These are editable quest settings, not app-wide rules.</p></section>`}
async function render(){const page=await ({today,train,dominance,quests,profile:profilePage}[screen]());$('#app').innerHTML=page+nav();bind()}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{screen=b.dataset.nav;render()});document.querySelectorAll('[data-water]').forEach(b=>b.onclick=()=>action('water',{amount:+b.dataset.water}));$('#water-custom')?.addEventListener('click',()=>{const n=prompt('Ounces to add');if(n!==null)action('water',{amount:+n||0})});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));document.querySelectorAll('[data-set]').forEach(b=>b.onclick=()=>action('complete-set',{exercise:b.dataset.set,reps:10,weight:0}));$('#export')?.addEventListener('click',async()=>{const file=new Blob([JSON.stringify(await exportDatabase(api),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=`kitty-quest-2-backup-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href)});$('#import')?.addEventListener('change',async e=>{const data=JSON.parse(await e.target.files[0].text());if(confirm('Restore this complete backup? Current Kitty Quest 2 data will be replaced.')){await importDatabase(api,data);profile=await bootstrap(api);day=await daily(api);render()}})}
function command(text){const t=text.toLowerCase();if(/add\s+\d+.*water/.test(t)){const n=+(t.match(/\d+/)||[0])[0];return action('water',{amount:n}).then(()=>`Added ${n} oz.`)}if(t.includes('move')&&t.includes('tonight'))return action('move-main-tonight').then(()=>"Main Workout moved to tonight.");if(t.includes("what's next")||t.includes('what am i doing'))return Promise.resolve('Your next priority is your Main Workout.');return Promise.resolve('Caelum understands the command layer, but that command is not available in Phase 1 yet.')}
$('#caelum-open').onclick=()=>$('#command-sheet').showModal();$('#command-run').onclick=async e=>{e.preventDefault();$('#command-result').textContent=await command($('#command-input').value);await render()};
async function init(){api=storeApi(await openDB());profile=await bootstrap(api);day=await daily(api);if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');render()}init();

