import {openDB,storeApi,bootstrap,daily,createMainSession} from './data.js';
import {exerciseLibrary,pct,updateWater} from './domain.mjs';
let api,profile,day,screen='today';const $=s=>document.querySelector(s);const bar=(n,t,label)=>`<div class="meta"><span>${label}</span><b>${pct(n,t)}%</b></div><div class="bar"><i style="width:${pct(n,t)}%"></i></div>`;
const session=()=>createMainSession(api,day,exerciseLibrary.slice(0,3));
async function water(amount){updateWater(day,amount);await api.put('daily',day);render()}
async function start(){const s=await session();if(s.status==='NOT_STARTED'){s.status='ACTIVE';await api.put('workouts',s)}screen='train';render()}
async function set(exercise){const s=await session();if(s.status==='COMPLETED')return;const sets=s.sets[exercise]||[];sets.push({id:crypto.randomUUID(),reps:10,weight:0,at:Date.now(),edits:[]});s.sets[exercise]=sets;if(s.exerciseIds.every(id=>(s.sets[id]||[]).length>=3)&&!s.completionTransactionId){s.status='COMPLETED';s.completedAt=Date.now();s.completionTransactionId=`main-${s.id}`;profile.xp+=75;profile.coins+=15;await api.put('profiles',profile)}else s.status='ACTIVE';await api.put('workouts',s);render()}
const nav=()=>`<nav class="nav"><div class="nav-inner">${[['today','⌂','TODAY'],['train','↗','TRAIN'],['dominance','◇','DOMINANCE'],['quests','☑','QUESTS'],['profile','◌','PROFILE']].map(x=>`<button class="${screen===x[0]?'active':''}" data-nav="${x[0]}"><i>${x[1]}</i>${x[2]}</button>`).join('')}</div></nav>`;
async function page(){const s=await session();if(screen==='today')return `<header class="top"><div><div class="eyebrow">CAELUM // ONLINE</div><h1>KITTY QUEST 2.0</h1><p>DOMINANCE // BODY MODULE</p></div><div class="orb">◉</div></header><section class="card"><div class="eyebrow">WATER</div><div class="metric">${day.water.consumed} / ${day.water.goal} oz</div>${bar(day.water.consumed,day.water.goal,'Daily hydration')}<div class="quick"><button class="ghost" data-water="-8">−8</button><button class="ghost" data-water="8">+8</button><button class="ghost" data-water="16">+16</button><button class="ghost" data-water="24">+24</button></div></section><section class="card"><div class="eyebrow">MAIN WORKOUT</div><h2>${s.status==='COMPLETED'?'✓ MAIN WORKOUT COMPLETE':'TOTAL BODY FOUNDATION'}</h2>${bar(Object.values(s.sets).reduce((n,x)=>n+x.length,0),9,'Set progress')}<button class="primary" id="start">${s.status==='COMPLETED'?'VIEW SESSION':'START / RESUME'}</button></section><div class="section">TODAY'S SCHEDULE</div><section class="schedule">${day.schedule.events.map(e=>`<article class="item"><time>${e.start}</time><span><b>${e.name}</b><small class="small">${e.context} · ${e.source}</small></span></article>`).join('')}</section>`;if(screen==='train')return `<h1>TRAIN</h1><div class="notice">Main Workout: ${s.status}</div>${exerciseLibrary.slice(0,3).map(e=>{const n=(s.sets[e.id]||[]).length;return `<section class="card"><h2>${e.name}</h2>${bar(n,3,'Working sets')}<p class="small">${e.safety}</p><button class="primary" ${n>=3?'disabled':''} data-set="${e.id}">${n>=3?'COMPLETE':'COMPLETE SET'}</button></section>`}).join('')}`;if(screen==='dominance')return `<h1>DOMINANCE</h1><section class="card"><h2>First Strict Pull-Up</h2>${bar(0,5,'Hangs → Scapular control → Assisted pull-ups → Negatives → Grip')}</section>`;if(screen==='quests')return `<h1>QUESTS</h1><section class="card"><b>Daily quests are being rebuilt from dated records.</b><p class="small">No duplicated checkboxes or disconnected completion states.</p></section>`;return `<h1>PROFILE</h1><section class="card"><h2>${profile.name}</h2><p>${profile.xp} XP · ${profile.coins} coins</p><p class="small">Legacy Kitty Quest data is snapshotted in this device's versioned database.</p></section>`}
async function render(){$('#app').innerHTML=await page()+nav();document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{screen=b.dataset.nav;render()});document.querySelectorAll('[data-water]').forEach(b=>b.onclick=()=>water(+b.dataset.water));$('#start')?.addEventListener('click',start);document.querySelectorAll('[data-set]').forEach(b=>b.onclick=()=>set(b.dataset.set))}
async function init(){api=storeApi(await openDB());profile=await bootstrap(api);day=await daily(api);render()}init().catch(error=>{$('#app').innerHTML=`<section class="card"><h1>Kitty Quest needs a refresh</h1><p>${error.message}</p></section>`;console.error(error)});

