import {id,todayKey,scheduleFor} from './domain.mjs';
const DB='kitty-quest-2',VERSION=1,STORES=['meta','profiles','daily','workouts','history','templates','goals','exercises','transactions'];
const req=x=>new Promise((resolve,reject)=>{x.onsuccess=()=>resolve(x.result);x.onerror=()=>reject(x.error)});
export async function openDB(){const request=indexedDB.open(DB,VERSION);request.onupgradeneeded=()=>{const db=request.result;STORES.forEach(s=>{if(!db.objectStoreNames.contains(s))db.createObjectStore(s,{keyPath:'id'})});const meta=request.transaction.objectStore('meta');meta.put({id:'schema',version:VERSION,migrations:[{version:1,at:Date.now(),name:'initial schema'}]})};return req(request)}
export const storeApi=db=>({get:(store,key)=>req(db.transaction(store).objectStore(store).get(key)),put:(store,value)=>req(db.transaction(store,'readwrite').objectStore(store).put(value)),all:(store)=>req(db.transaction(store).objectStore(store).getAll()),clear:(store)=>req(db.transaction(store,'readwrite').objectStore(store).clear())});
export async function bootstrap(api){let profile=await api.get('profiles','me');if(!profile){const legacy=localStorage.getItem('kitty-quest-web-v3');let legacyData=null,legacyError=null;try{legacyData=legacy?JSON.parse(legacy):null}catch(error){legacyError=String(error)}await api.put('meta',{id:'legacy-snapshot',capturedAt:Date.now(),sourceKey:'kitty-quest-web-v3',data:legacyData,legacyError,verified:false});profile={id:'me',name:'Zari',xp:0,coins:0,streak:0,createdAt:Date.now(),caelumMode:'COMMAND'};await api.put('profiles',profile);await api.put('goals',{id:'total-body-dominance',name:'Total Body Dominance',dependencies:[]});await api.put('goals',{id:'first-strict-pullup',name:'First Strict Pull-Up',dependencies:['hangs','scapular-control','assisted-pullups','negatives','grip-milestones']});await api.put('goals',{id:'transformation-initial',name:'12-Week Transformation Quest',type:'TRANSFORMATION',config:{startWeight:216,targetRange:[192,204],laterMilestone:175,durationWeeks:12},dependencies:[]})}return profile}
export async function daily(api,date=todayKey()){let record=await api.get('daily',date);if(!record){record={id:date,date,water:{goal:200,consumed:0,entries:[]},routine:{morning:[],night:[]},schedule:scheduleFor(new Date().getDay(),date),mainWorkoutId:null,createdAt:Date.now()};await api.put('daily',record)}return record}
export async function exportDatabase(api){const data={format:'kitty-quest-2-backup',version:VERSION,exportedAt:new Date().toISOString(),stores:{}};for(const s of STORES)data.stores[s]=await api.all(s);return data}
export async function importDatabase(api,data){if(data?.format!=='kitty-quest-2-backup')throw new Error('That is not a Kitty Quest 2 backup.');for(const s of STORES){await api.clear(s);for(const item of data.stores?.[s]||[])await api.put(s,item)}}
export async function createMainSession(api,dailyRecord,exercises){if(dailyRecord.mainWorkoutId){const old=await api.get('workouts',dailyRecord.mainWorkoutId);if(old)return old}const session={id:id(),type:'MAIN',date:dailyRecord.date,status:'NOT_STARTED',exerciseIds:exercises.map(x=>x.id),sets:{},createdAt:Date.now(),pausedAt:null,completedAt:null,completionTransactionId:null,editLog:[]};dailyRecord.mainWorkoutId=session.id;await api.put('daily',dailyRecord);await api.put('workouts',session);return session}

