export const todayKey=()=>new Date().toLocaleDateString('en-CA');
export const id=()=>crypto.randomUUID();
export const pct=(value,target)=>Math.max(0,Math.min(100,Math.round((value/Math.max(target,1))*100)));
export const workoutComplete=session=>session.status==='COMPLETED';
export function completeOnce(session, transactionId){if(workoutComplete(session)||session.completionTransactionId)return false;session.status='COMPLETED';session.completedAt=Date.now();session.completionTransactionId=transactionId;return true}
export function updateWater(daily,amount){const next=Math.max(0,Math.min(daily.water.goal,daily.water.consumed+amount));daily.water.entries.push({id:id(),amount,at:Date.now()});daily.water.consumed=next;return daily}
export function editHistoricalSet(set,patch,reason){if(!reason?.trim())throw new Error('A correction reason is required.');const before={...set};Object.assign(set,patch);set.edits ||= [];set.edits.push({id:id(),at:Date.now(),reason,before,after:{...patch}});return set}
export function scheduleFor(day,date){const events=[];const add=(name,start,end,context,source,fixed=true)=>events.push({id:id(),name,start,end,context,source,fixed,status:'PLANNED'});if(day>=1&&day<=4){add('Morning routine','5:30 AM','5:55 AM','HOME','routine');add('Meal 1','5:55 AM','6:15 AM','HOME','nutrition',false);add('Leave for school','6:30 AM','9:30 AM','COMMUTE','school');add('Class','9:30 AM','10:45 AM','SCHOOL','school');add('Drive to gym','10:45 AM','12:45 PM','COMMUTE','school');add('Main Workout','12:45 PM','2:00 PM','GYM','training',false);add('Meal 2','2:15 PM','2:45 PM','GYM','nutrition',false);add('Meal 3','7:00 PM','7:30 PM','HOME','nutrition',false)}else{add('Morning routine','8:00 AM','8:45 AM','HOME','routine');add('Meal 1','8:45 AM','9:15 AM','HOME','nutrition',false);add('Main Workout','10:00 AM','11:15 AM',day===0?'HOME':'GYM','training',false);add('Meal 2','1:00 PM','1:30 PM','ANYWHERE','nutrition',false);add('Meal 3','7:00 PM','7:30 PM','HOME','nutrition',false)}return {id:id(),date,templateVersion:1,events,createdAt:Date.now()}}
export const exerciseLibrary=[
 {id:'leg-press',name:'Leg Press',muscles:['quads','glutes'],equipment:['leg press'],alternatives:['Goblet Squat','Bodyweight Squat'],regressions:['Bodyweight Squat'],progressions:['Higher resistance'],safety:'Keep knees tracking with toes; use a pain-free range.',dominance:{type:'controlledWorkingSets',targetSets:4,targetReps:10}},
 {id:'chest-press',name:'Machine Chest Press',muscles:['chest','triceps'],equipment:['chest press'],alternatives:['Dumbbell Press','Incline Push-up'],regressions:['Wall Push-up'],progressions:['Higher resistance'],safety:'Set handles at mid-chest and avoid painful shoulder range.',dominance:{type:'controlledWorkingSets',targetSets:4,targetReps:10}},
 {id:'lat-pulldown',name:'Lat Pulldown',muscles:['back','biceps'],equipment:['cable'],alternatives:['Band Pulldown','Assisted Pull-up'],regressions:['Band Pulldown'],progressions:['Assisted Pull-up'],safety:'Keep ribs down and do not pull behind the neck.',dominance:{type:'controlledWorkingSets',targetSets:4,targetReps:10}},
 {id:'assisted-pullup',name:'Assisted Pull-up',muscles:['back','biceps','grip'],equipment:['assisted pull-up'],alternatives:['Lat Pulldown','Negative Pull-up'],regressions:['Scapular Pull'],progressions:['Negative Pull-up','Strict Pull-up'],safety:'Use controlled assistance; stop for sharp shoulder or elbow pain.',dominance:{type:'pullupPath',targetSessions:8}}
];
export const pullupGoal={id:'first-strict-pullup',name:'First Strict Pull-Up',dependsOn:['hangs','scapular-control','assisted-pullups','negatives','grip-milestones']};

